### ISSUE TITLE
JIT recompiler

### ISSUE THREAD

**Issue by SoniEx2** [ds84182/LuaVM#2]
Would it be possible to add a JIT recompiler in order to make LuaVM run faster?

**Comment by ds84182** [comment]
Yes, but later. My main efforts are focused on the decompiler.

**Comment by ds84182** [comment]
I've just open sourced Decompiler3. Decompiler3 tries to get close to the original source form of the program (although there are edge cases everywhere). Decompiler3 is fast enough for a JIT, so technically I can close this.

**Comment by SoniEx2** [comment]
I wasn't thinking of decompilation. Decompilation doesn't let me do sandboxing, so it's useless.
